name: Render Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Render CLI
        run: |
          pip install render-python
        env:
          RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}

      - name: Set Python Version on Render
        run: |
          render env set -e PYTHON_VERSION=3.9.11
        env:
          RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}